// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjvqjqdxyfyimpdxxwxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqdnFqcWR4eWZ5aW1wZHh4d3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0MTczOTksImV4cCI6MjA5Nzk5MzM5OX0.tUH6H-00H7wujlVdJwlK8U_wpV_iCOfB9zNWqh78EZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});